---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
  requiredStorage: 20
  requiredRam: 1.5
  internetCheckUrl: https://archlinux.org
  check: [ storage, ram, power, internet, root ]
  required: [ storage, ram, root ]
