on:
  push:
    branches: [main]

name: Build ISO

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install archiso deps
        run: pacman -Syu --noconfirm archiso grub dosfstools edk2-ovmf mtools libisoburn erofs-utils

      - name: Bootstrap missing archiso profile files
        run: |
          for f in pacman.conf syslinux grub efiboot; do
            if [ ! -e "profile/$f" ]; then
              cp -r "/usr/share/archiso/configs/releng/$f" "profile/$f"
            fi
          done

      - name: Set executable permissions
        run: find profile/airootfs -type f -name "*.sh" -exec chmod +x {} \;

      - name: Build ISO
        run: mkarchiso -v -w work/ -o out/ profile/

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-iso
          path: out/
